server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saga_inventory?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

